package com.digo.pojo;

// Generated Mar 10, 2013 2:27:49 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Account generated by hbm2java
 */
public class Account implements java.io.Serializable {

	private String accountId;
	private User user;
	private String accountPasswords;
	private Date initTime;
	private char accountStatus;
	private int balance;
	private String remark;
	private Set recordses = new HashSet(0);

	public Account() {
	}

	public Account(User user, String accountPasswords, Date initTime,
			char accountStatus, int balance, String remark) {
		this.user = user;
		this.accountPasswords = accountPasswords;
		this.initTime = initTime;
		this.accountStatus = accountStatus;
		this.balance = balance;
		this.remark = remark;
	}

	public Account(User user, String accountPasswords, Date initTime,
			char accountStatus, int balance, String remark, Set recordses) {
		this.user = user;
		this.accountPasswords = accountPasswords;
		this.initTime = initTime;
		this.accountStatus = accountStatus;
		this.balance = balance;
		this.remark = remark;
		this.recordses = recordses;
	}

	public String getAccountId() {
		return this.accountId;
	}

	public void setAccountId(String accountId) {
		this.accountId = accountId;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public String getAccountPasswords() {
		return this.accountPasswords;
	}

	public void setAccountPasswords(String accountPasswords) {
		this.accountPasswords = accountPasswords;
	}

	public Date getInitTime() {
		return this.initTime;
	}

	public void setInitTime(Date initTime) {
		this.initTime = initTime;
	}

	public char getAccountStatus() {
		return this.accountStatus;
	}

	public void setAccountStatus(char accountStatus) {
		this.accountStatus = accountStatus;
	}

	public int getBalance() {
		return this.balance;
	}

	public void setBalance(int balance) {
		this.balance = balance;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public Set getRecordses() {
		return this.recordses;
	}

	public void setRecordses(Set recordses) {
		this.recordses = recordses;
	}

}
