package com.digo.pojo;

// Generated Mar 10, 2013 2:27:49 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Goods generated by hbm2java
 */
public class Goods implements java.io.Serializable {

	private String goodsId;
	private User user;
	private String goodsType;
	private String goodsName;
	private float goodsPrice;
	private int goodsCount;
	private String goodsUnit;
	private String goodsDes;
	private String goodsInfo;
	private String goodsImage;
	private Date initTime;
	private String promotionValue;
	private char promotionKey;
	private String remark;
	private Set orderrelations = new HashSet(0);
	private Set comments = new HashSet(0);

	public Goods() {
	}

	public Goods(String goodsId, User user, String goodsType, String goodsName,
			float goodsPrice, int goodsCount, String goodsUnit,
			String goodsDes, String goodsInfo, String goodsImage,
			Date initTime, String promotionValue, char promotionKey,
			String remark) {
		this.goodsId = goodsId;
		this.user = user;
		this.goodsType = goodsType;
		this.goodsName = goodsName;
		this.goodsPrice = goodsPrice;
		this.goodsCount = goodsCount;
		this.goodsUnit = goodsUnit;
		this.goodsDes = goodsDes;
		this.goodsInfo = goodsInfo;
		this.goodsImage = goodsImage;
		this.initTime = initTime;
		this.promotionValue = promotionValue;
		this.promotionKey = promotionKey;
		this.remark = remark;
	}

	public Goods(String goodsId, User user, String goodsType, String goodsName,
			float goodsPrice, int goodsCount, String goodsUnit,
			String goodsDes, String goodsInfo, String goodsImage,
			Date initTime, String promotionValue, char promotionKey,
			String remark, Set orderrelations, Set comments) {
		this.goodsId = goodsId;
		this.user = user;
		this.goodsType = goodsType;
		this.goodsName = goodsName;
		this.goodsPrice = goodsPrice;
		this.goodsCount = goodsCount;
		this.goodsUnit = goodsUnit;
		this.goodsDes = goodsDes;
		this.goodsInfo = goodsInfo;
		this.goodsImage = goodsImage;
		this.initTime = initTime;
		this.promotionValue = promotionValue;
		this.promotionKey = promotionKey;
		this.remark = remark;
		this.orderrelations = orderrelations;
		this.comments = comments;
	}

	public String getGoodsId() {
		return this.goodsId;
	}

	public void setGoodsId(String goodsId) {
		this.goodsId = goodsId;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public String getGoodsType() {
		return this.goodsType;
	}

	public void setGoodsType(String goodsType) {
		this.goodsType = goodsType;
	}

	public String getGoodsName() {
		return this.goodsName;
	}

	public void setGoodsName(String goodsName) {
		this.goodsName = goodsName;
	}

	public float getGoodsPrice() {
		return this.goodsPrice;
	}

	public void setGoodsPrice(float goodsPrice) {
		this.goodsPrice = goodsPrice;
	}

	public int getGoodsCount() {
		return this.goodsCount;
	}

	public void setGoodsCount(int goodsCount) {
		this.goodsCount = goodsCount;
	}

	public String getGoodsUnit() {
		return this.goodsUnit;
	}

	public void setGoodsUnit(String goodsUnit) {
		this.goodsUnit = goodsUnit;
	}

	public String getGoodsDes() {
		return this.goodsDes;
	}

	public void setGoodsDes(String goodsDes) {
		this.goodsDes = goodsDes;
	}

	public String getGoodsInfo() {
		return this.goodsInfo;
	}

	public void setGoodsInfo(String goodsInfo) {
		this.goodsInfo = goodsInfo;
	}

	public String getGoodsImage() {
		return this.goodsImage;
	}

	public void setGoodsImage(String goodsImage) {
		this.goodsImage = goodsImage;
	}

	public Date getInitTime() {
		return this.initTime;
	}

	public void setInitTime(Date initTime) {
		this.initTime = initTime;
	}

	public String getPromotionValue() {
		return this.promotionValue;
	}

	public void setPromotionValue(String promotionValue) {
		this.promotionValue = promotionValue;
	}

	public char getPromotionKey() {
		return this.promotionKey;
	}

	public void setPromotionKey(char promotionKey) {
		this.promotionKey = promotionKey;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public Set getOrderrelations() {
		return this.orderrelations;
	}

	public void setOrderrelations(Set orderrelations) {
		this.orderrelations = orderrelations;
	}

	public Set getComments() {
		return this.comments;
	}

	public void setComments(Set comments) {
		this.comments = comments;
	}

}
