package com.digo.pojo;

// Generated Mar 10, 2013 2:27:49 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Orders generated by hbm2java
 */
public class Orders implements java.io.Serializable {

	private String orderId;
	private User user;
	private Date orderTime;
	private String receiveAddrId;
	private char orderStatus;
	private Set orderrelations = new HashSet(0);

	public Orders() {
	}

	public Orders(String orderId, User user, Date orderTime,
			String receiveAddrId, char orderStatus) {
		this.orderId = orderId;
		this.user = user;
		this.orderTime = orderTime;
		this.receiveAddrId = receiveAddrId;
		this.orderStatus = orderStatus;
	}

	public Orders(String orderId, User user, Date orderTime,
			String receiveAddrId, char orderStatus, Set orderrelations) {
		this.orderId = orderId;
		this.user = user;
		this.orderTime = orderTime;
		this.receiveAddrId = receiveAddrId;
		this.orderStatus = orderStatus;
		this.orderrelations = orderrelations;
	}

	public String getOrderId() {
		return this.orderId;
	}

	public void setOrderId(String orderId) {
		this.orderId = orderId;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public Date getOrderTime() {
		return this.orderTime;
	}

	public void setOrderTime(Date orderTime) {
		this.orderTime = orderTime;
	}

	public String getReceiveAddrId() {
		return this.receiveAddrId;
	}

	public void setReceiveAddrId(String receiveAddrId) {
		this.receiveAddrId = receiveAddrId;
	}

	public char getOrderStatus() {
		return this.orderStatus;
	}

	public void setOrderStatus(char orderStatus) {
		this.orderStatus = orderStatus;
	}

	public Set getOrderrelations() {
		return this.orderrelations;
	}

	public void setOrderrelations(Set orderrelations) {
		this.orderrelations = orderrelations;
	}

}
