package com.digo.pojo;

// Generated Mar 10, 2013 2:27:49 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Power generated by hbm2java
 */
public class Power implements java.io.Serializable {

	private String powerId;
	private String powerContent;
	private String powerDes;
	private char powerType;
	private Set rolerelations = new HashSet(0);

	public Power() {
	}

	public Power(String powerId, String powerContent, String powerDes,
			char powerType) {
		this.powerId = powerId;
		this.powerContent = powerContent;
		this.powerDes = powerDes;
		this.powerType = powerType;
	}

	public Power(String powerId, String powerContent, String powerDes,
			char powerType, Set rolerelations) {
		this.powerId = powerId;
		this.powerContent = powerContent;
		this.powerDes = powerDes;
		this.powerType = powerType;
		this.rolerelations = rolerelations;
	}

	public String getPowerId() {
		return this.powerId;
	}

	public void setPowerId(String powerId) {
		this.powerId = powerId;
	}

	public String getPowerContent() {
		return this.powerContent;
	}

	public void setPowerContent(String powerContent) {
		this.powerContent = powerContent;
	}

	public String getPowerDes() {
		return this.powerDes;
	}

	public void setPowerDes(String powerDes) {
		this.powerDes = powerDes;
	}

	public char getPowerType() {
		return this.powerType;
	}

	public void setPowerType(char powerType) {
		this.powerType = powerType;
	}

	public Set getRolerelations() {
		return this.rolerelations;
	}

	public void setRolerelations(Set rolerelations) {
		this.rolerelations = rolerelations;
	}

}
