package com.digo.pojo;

// Generated Mar 10, 2013 2:27:49 PM by Hibernate Tools 3.4.0.CR1

/**
 * Receiveaddress generated by hbm2java
 */
public class Receiveaddress implements java.io.Serializable {

	private String receiveAddrId;
	private User user;
	private String receiveName;
	private String city;
	private String street;
	private String phone;
	private String zipCode;
	private String email;
	private char deliveryType;
	private char payType;

	public Receiveaddress() {
	}

	public Receiveaddress(String receiveAddrId, User user, String receiveName,
			String city, String street, String phone, String zipCode,
			String email, char deliveryType, char payType) {
		this.receiveAddrId = receiveAddrId;
		this.user = user;
		this.receiveName = receiveName;
		this.city = city;
		this.street = street;
		this.phone = phone;
		this.zipCode = zipCode;
		this.email = email;
		this.deliveryType = deliveryType;
		this.payType = payType;
	}

	public String getReceiveAddrId() {
		return this.receiveAddrId;
	}

	public void setReceiveAddrId(String receiveAddrId) {
		this.receiveAddrId = receiveAddrId;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public String getReceiveName() {
		return this.receiveName;
	}

	public void setReceiveName(String receiveName) {
		this.receiveName = receiveName;
	}

	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public String getStreet() {
		return this.street;
	}

	public void setStreet(String street) {
		this.street = street;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getZipCode() {
		return this.zipCode;
	}

	public void setZipCode(String zipCode) {
		this.zipCode = zipCode;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public char getDeliveryType() {
		return this.deliveryType;
	}

	public void setDeliveryType(char deliveryType) {
		this.deliveryType = deliveryType;
	}

	public char getPayType() {
		return this.payType;
	}

	public void setPayType(char payType) {
		this.payType = payType;
	}

}
