package com.digo.pojo;

// Generated Mar 10, 2013 2:27:49 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Records generated by hbm2java
 */
public class Records implements java.io.Serializable {

	private String recordsId;
	private Account account;
	private String orderId;
	private char recordsType;
	private int recordsNumber;
	private Date recordsTime;
	private String remark;

	public Records() {
	}

	public Records(String recordsId, Account account, String orderId,
			char recordsType, int recordsNumber, Date recordsTime, String remark) {
		this.recordsId = recordsId;
		this.account = account;
		this.orderId = orderId;
		this.recordsType = recordsType;
		this.recordsNumber = recordsNumber;
		this.recordsTime = recordsTime;
		this.remark = remark;
	}

	
	/**
	 * @return 订单id
	 */
	public String getRecordsId() {
		return this.recordsId;
	}

	public void setRecordsId(String recordsId) {
		this.recordsId = recordsId;
	}

	/**
	 * @return 账户
	 */
	public Account getAccount() {
		return this.account;
	}

	public void setAccount(Account account) {
		this.account = account;
	}

	public String getOrderId() {
		return this.orderId;
	}

	public void setOrderId(String orderId) {
		this.orderId = orderId;
	}

	/**
	 * @return 配送时间-1任意，0周末，1工作日
	 */
	public char getRecordsType() {
		return this.recordsType;
	}

	public void setRecordsType(char recordsType) {
		this.recordsType = recordsType;
	}

	/**
	 * @return 1：只傍晚送货，0
	 */
	public int getRecordsNumber() {
		return this.recordsNumber;
	}

	public void setRecordsNumber(int recordsNumber) {
		this.recordsNumber = recordsNumber;
	}

	public Date getRecordsTime() {
		return this.recordsTime;
	}

	public void setRecordsTime(Date recordsTime) {
		this.recordsTime = recordsTime;
	}

	/**
	 * @return 超市配送时间
	 */
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

}
