package com.digo.pojo;

// Generated Mar 10, 2013 2:27:49 PM by Hibernate Tools 3.4.0.CR1

/**
 * Rolerelation generated by hbm2java
 */
public class Rolerelation implements java.io.Serializable {

	private String roleRelationId;
	private Power power;
	private Role role;

	public Rolerelation() {
	}

	public Rolerelation(String roleRelationId, Power power, Role role) {
		this.roleRelationId = roleRelationId;
		this.power = power;
		this.role = role;
	}

	public String getRoleRelationId() {
		return this.roleRelationId;
	}

	public void setRoleRelationId(String roleRelationId) {
		this.roleRelationId = roleRelationId;
	}

	public Power getPower() {
		return this.power;
	}

	public void setPower(Power power) {
		this.power = power;
	}

	public Role getRole() {
		return this.role;
	}

	public void setRole(Role role) {
		this.role = role;
	}

}
