package com.digo.pojo;

// Generated Mar 10, 2013 2:27:49 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable {

	private String userId;
	private String username;
	private String userpasswords;
	private String realname;
	private String roleId;
	private String identityNumber;
	private String email;
	private String phone;
	private int points;
	private short creditLevel;
	private Account account;
	private Set orderses = new HashSet(0);
	private Set goodses = new HashSet(0);
	private Set comments = new HashSet(0);
	private Set receiveaddresses = new HashSet(0);

	public User() {
	}

	public User(String userId, String username, String userpasswords,
			String realname, String roleId, String identityNumber,
			String email, String phone, int points, short creditLevel) {
		this.userId = userId;
		this.username = username;
		this.userpasswords = userpasswords;
		this.realname = realname;
		this.roleId = roleId;
		this.identityNumber = identityNumber;
		this.email = email;
		this.phone = phone;
		this.points = points;
		this.creditLevel = creditLevel;
	}

	public User(String userId, String username, String userpasswords,
			String realname, String roleId, String identityNumber,
			String email, String phone, int points, short creditLevel,
			Account account, Set orderses, Set goodses, Set comments,
			Set receiveaddresses) {
		this.userId = userId;
		this.username = username;
		this.userpasswords = userpasswords;
		this.realname = realname;
		this.roleId = roleId;
		this.identityNumber = identityNumber;
		this.email = email;
		this.phone = phone;
		this.points = points;
		this.creditLevel = creditLevel;
		this.account = account;
		this.orderses = orderses;
		this.goodses = goodses;
		this.comments = comments;
		this.receiveaddresses = receiveaddresses;
	}

	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getUserpasswords() {
		return this.userpasswords;
	}

	public void setUserpasswords(String userpasswords) {
		this.userpasswords = userpasswords;
	}

	public String getRealname() {
		return this.realname;
	}

	public void setRealname(String realname) {
		this.realname = realname;
	}

	public String getRoleId() {
		return this.roleId;
	}

	public void setRoleId(String roleId) {
		this.roleId = roleId;
	}

	public String getIdentityNumber() {
		return this.identityNumber;
	}

	public void setIdentityNumber(String identityNumber) {
		this.identityNumber = identityNumber;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public int getPoints() {
		return this.points;
	}

	public void setPoints(int points) {
		this.points = points;
	}

	public short getCreditLevel() {
		return this.creditLevel;
	}

	public void setCreditLevel(short creditLevel) {
		this.creditLevel = creditLevel;
	}

	public Account getAccount() {
		return this.account;
	}

	public void setAccount(Account account) {
		this.account = account;
	}

	public Set getOrderses() {
		return this.orderses;
	}

	public void setOrderses(Set orderses) {
		this.orderses = orderses;
	}

	public Set getGoodses() {
		return this.goodses;
	}

	public void setGoodses(Set goodses) {
		this.goodses = goodses;
	}

	public Set getComments() {
		return this.comments;
	}

	public void setComments(Set comments) {
		this.comments = comments;
	}

	public Set getReceiveaddresses() {
		return this.receiveaddresses;
	}

	public void setReceiveaddresses(Set receiveaddresses) {
		this.receiveaddresses = receiveaddresses;
	}

}
